### ISSUE TITLE
Add guide on configuring port and hostname

### ISSUE THREAD

**Issue by harryge00** [spring-guides/gs-messaging-redis#20]
I am not familiar with spring framework. I tried to use `setHostname/setPort` or `RedisStandaloneConfiguration` to configure host/port, but it always reported error ...
I think as guide for spring, it will be beneficial adding example on configuring host/port instead of using the default config. Thanks

**Comment by Buzzardo** [comment]
I think we shouldn't change the heading, but I also think it's a reasonable request to add how to set the host and port. Thanks for the feedback, @harryge00 

Gary: If you're not the right person to describe that, please let me know. Also, if you want help with the wording, please let me know. I'll review it anyway, though. Thanks much.

**Comment by garyrussell** [comment]
I am not the right person (@mp911de , or someone from the Boot team?). 

However, I would suggest a doc link to https://docs.spring.io/spring-boot/docs/current/reference/html/spring-boot-features.html#boot-features-redis and to https://docs.spring.io/spring-boot/docs/current/reference/html/appendix-application-properties.html#data-properties (scroll down to `spring.redis.host`). 

I have an [open request to make the anchors for those properties more granular](https://github.com/spring-projects/spring-boot/issues/16267). Vote it up!!

**Comment by dsyer** [comment]
+1 for a doc link. And the same for rabbit and Kafka guides.

**Comment by harryge00** [comment]
I finally figured out a way to configure 😂：
```
       # Add another function:
       @Bean
	public RedisConnectionFactory redisConnectionFactory() {
		RedisStandaloneConfiguration redisConfig = new RedisStandaloneConfiguration("1.2.3.4", 6379);
		redisConfig.setPassword(RedisPassword.of("somepassword"));
		return new LettuceConnectionFactory(redisConfig);
	}
```
Using `application.properties` would be more elegant though. Thanks for your reply.

**Comment by mp911de** [comment]
`RedisConnectionFactory` is configured by Spring Boot, so +1 to add a link to the Boot docs that explain Redis properties related to the endpoint configuration.

**Comment by Buzzardo** [comment]
I added https://github.com/spring-guides/gs-messaging-redis/issues/26 to replace this one.
