### ISSUE TITLE
Upgrade Spring Boot to the latest version

### ISSUE THREAD

**Issue by robertmcnees** [spring-guides/gs-messaging-redis#25]
Update the guide to use the most recent Spring Boot version.

Files that require changes are:
```
initial/build.gradle
initial/pom.xml
complete/build.gradle
complete/pom.xml
```

**Comment by zhangwt-cn** [comment]
@robertmcnees I've done it, please help review it #27

**Comment by robertmcnees** [comment]
Dependabot is now being used in this repository to update versions.
