### ISSUE TITLE
Add a link to the Spring Boot docs about Redis configuration.

### ISSUE THREAD

**Issue by Buzzardo** [spring-guides/gs-messaging-redis#26]
As the discussion in https://github.com/spring-guides/gs-messaging-redis/issues/20 indicates, it would be good to add a link to the Spring Boot docs that have to do with Redis configuration.

This is a good one for a first-time committer.

**Comment by zhangwt-cn** [comment]
Hello, I want to try to complete this work, but I don't know where this document needs to be added to this project.

**Comment by Buzzardo** [comment]
I would add it as a note at the top of the "Create a Redis Message Receiver" section.

**Comment by zhangwt-cn** [comment]
@Buzzardo I've done it, please help review it #27

**Comment by robertmcnees** [comment]
In the PR #32 I added the link specified in #20. The guide now uses Spring Boot Docker Compose support, so using `application.properties` to configure connection details is no longer required, if it ever was. I dropped the link in the NOTE section, so hopefully readers will be able to easily find more information if they choose.
