### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by hygl** [spring-guides/gs-messaging-redis#3]
The gs-messaging-redis guide has missing dependencies. 

```
 java.lang.ClassNotFoundException: redis.clients.util.Pool
```

When I add the missing dependency 

```
    <dependency>
            <groupId>redis.clients</groupId>
            <artifactId>jedis</artifactId>
            <version>2.4.1</version>
        </dependency>
```

 I get another dependency error, that I did not investigate further:

```
java.lang.ClassNotFoundException: org.apache.commons.pool.impl.GenericObjectPool$Config
```

**Comment by pavs94** [comment]
I'm having the same error

**Comment by mp911de** [comment]
Using Jedis requires adding the `commons-pool2` dependency. Spring Boot 2 ships with Lettuce as default client (@gregturn we should reflect this in the readme by replacing Jedis with Lettuce).
