### ISSUE TITLE
Remove reference to Redis license

### ISSUE THREAD

**Issue by mbhave** [spring-guides/gs-messaging-redis#30]
With the Redis license changes, this statement is no longer accurate `Redis is an open source, BSD-licensed, key-value data store that also comes with a messaging system.` I think we should just be able to remove this sentence.

**Comment by robertmcnees** [comment]
Addressed with [this commit](https://github.com/spring-guides/gs-messaging-redis/pull/31/commits/23c6888fe42893602b849393ce2e7bd1aebcc3dd) in PR #31
